/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Media = {
  _type: 'media'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  videoUrl?: string
}

export type CarouselSection = {
  _type: 'carouselSection'
  title?: string
  items?: Array<{
    media: Media
    caption?: string
    _key: string
  }>
}

export type Cta = {
  _type: 'cta'
  title: string
  link?: Link
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<
        {
          _key: string
        } & Link
      >
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type Seo = {
  _type: 'seo'
  title?: string
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Tag = {
  _id: string
  _type: 'tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Annotation = {
  _id: string
  _type: 'annotation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  content: string
  reviewerName?: string
  status: 'new' | 'in-progress' | 'done'
  annotationId?: string
  pageUrl?: string
  positionX?: number
  positionY?: number
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: string
}

export type AboutPageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'aboutPage'
}

export type HomePageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'homePage'
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type ProjectsIndexReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'projectsIndex'
}

export type Link = {
  _type: 'link'
  text?: string
  type: string
  internalLink?:
    | AboutPageReference
    | HomePageReference
    | PageReference
    | ProjectReference
    | ProjectsIndexReference
  url?: string
  email?: string
  phone?: string
  value?: string
  blank?: boolean
  parameters?: string
  anchor?: string
}

export type TagReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'tag'
}

export type ProjectsIndex = {
  _id: string
  _type: 'projectsIndex'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  filters?: Array<
    {
      _key: string
    } & TagReference
  >
  seo?: Seo
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRank?: string
  name: string
  slug: Slug
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  description?: string
  tags?: Array<
    {
      _key: string
    } & TagReference
  >
  gallery?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    caption?: string
    _type: 'image'
    _key: string
  }>
  sections?: Array<
    {
      _key: string
    } & CarouselSection
  >
  ctas?: Array<
    {
      _key: string
    } & Cta
  >
  seo?: Seo
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  content?: BlockContent
  seo?: Seo
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: string
  featuredProjects?: Array<
    {
      _key: string
    } & ProjectReference
  >
  content?: BlockContent
  seo?: Seo
}

export type AboutPage = {
  _id: string
  _type: 'aboutPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  content?: BlockContent
  seo?: Seo
}

export type Color = {
  _type: 'color'
  hex?: string
  alpha?: number
  hsl?: HslaColor
  hsv?: HsvaColor
  rgb?: RgbaColor
}

export type RgbaColor = {
  _type: 'rgbaColor'
  r?: number
  g?: number
  b?: number
  a?: number
}

export type HsvaColor = {
  _type: 'hsvaColor'
  h?: number
  s?: number
  v?: number
  a?: number
}

export type HslaColor = {
  _type: 'hslaColor'
  h?: number
  s?: number
  l?: number
  a?: number
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Media
  | CarouselSection
  | Cta
  | BlockContent
  | Seo
  | Tag
  | Slug
  | Annotation
  | Settings
  | AboutPageReference
  | HomePageReference
  | PageReference
  | ProjectReference
  | ProjectsIndexReference
  | Link
  | TagReference
  | ProjectsIndex
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Page
  | HomePage
  | AboutPage
  | Color
  | RgbaColor
  | HsvaColor
  | HslaColor
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../frontend/src/data/sanity/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "settings"][0]
export type SETTINGS_QUERY_RESULT = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: string
} | null

// Source: ../frontend/src/data/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage"][0] {  _id,  _type,  title,  description,  content[] {   ...,  markDefs[] {    ...,    _type == "link" => {   ...,  internalLink->{ _type, _id, "slug": slug.current, title } }  } },  featuredProjects[]->{   _id,  _type,  name,  slug,  coverImage {   asset->{    _id,    url,    mimeType,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  hotspot,  crop },  description },    seo {    title,    description,    image  }}
export type HOME_PAGE_QUERY_RESULT = {
  _id: string
  _type: 'homePage'
  title: string
  description: string | null
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs: Array<{
          _key: string
          _type: 'link'
          text?: string
          type: string
          internalLink:
            | {
                _type: 'aboutPage'
                _id: string
                slug: null
                title: string
              }
            | {
                _type: 'homePage'
                _id: string
                slug: null
                title: string
              }
            | {
                _type: 'page'
                _id: string
                slug: string
                title: string
              }
            | {
                _type: 'project'
                _id: string
                slug: string
                title: null
              }
            | {
                _type: 'projectsIndex'
                _id: string
                slug: null
                title: string
              }
            | null
          url?: string
          email?: string
          phone?: string
          value?: string
          blank?: boolean
          parameters?: string
          anchor?: string
        }> | null
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
        markDefs: null
      }
  > | null
  featuredProjects: Array<{
    _id: string
    _type: 'project'
    name: string
    slug: Slug
    coverImage: {
      asset: {
        _id: string
        url: string | null
        mimeType: string | null
        metadata: {
          lqip: string | null
          dimensions: {
            width: number
            height: number
            aspectRatio: number
          } | null
        } | null
      } | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
    }
    description: string | null
  }> | null
  seo: {
    title: string | null
    description: string | null
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
  } | null
} | null

// Source: ../frontend/src/data/sanity/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0] {  _id,  _type,  title,  slug,  content[] {   ...,  markDefs[] {    ...,    _type == "link" => {   ...,  internalLink->{ _type, _id, "slug": slug.current, title } }  } },    seo {    title,    description,    image  }}
export type PAGE_QUERY_RESULT = {
  _id: string
  _type: 'page'
  title: string
  slug: Slug
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs: Array<{
          _key: string
          _type: 'link'
          text?: string
          type: string
          internalLink:
            | {
                _type: 'aboutPage'
                _id: string
                slug: null
                title: string
              }
            | {
                _type: 'homePage'
                _id: string
                slug: null
                title: string
              }
            | {
                _type: 'page'
                _id: string
                slug: string
                title: string
              }
            | {
                _type: 'project'
                _id: string
                slug: string
                title: null
              }
            | {
                _type: 'projectsIndex'
                _id: string
                slug: null
                title: string
              }
            | null
          url?: string
          email?: string
          phone?: string
          value?: string
          blank?: boolean
          parameters?: string
          anchor?: string
        }> | null
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
        markDefs: null
      }
  > | null
  seo: {
    title: string | null
    description: string | null
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
  } | null
} | null

// Source: ../frontend/src/data/sanity/queries.ts
// Variable: ALL_PAGES_QUERY
// Query: *[_type == "page" && defined(slug.current)] {  _id,  title,  slug}
export type ALL_PAGES_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: Slug
}>

// Source: ../frontend/src/data/sanity/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {      _id,  _type,  name,  slug,  coverImage {   asset->{    _id,    url,    mimeType,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  hotspot,  crop },  description,  gallery[] {      _key,    asset->{    _id,    url,    mimeType,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  hotspot,  crop,  caption  },  tags[]->{      _id,  _type,  name,  "slug": slug.current  },    seo {    title,    description,    image  }}
export type PROJECT_QUERY_RESULT = {
  _id: string
  _type: 'project'
  name: string
  slug: Slug
  coverImage: {
    asset: {
      _id: string
      url: string | null
      mimeType: string | null
      metadata: {
        lqip: string | null
        dimensions: {
          width: number
          height: number
          aspectRatio: number
        } | null
      } | null
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  }
  description: string | null
  gallery: Array<{
    _key: string
    asset: {
      _id: string
      url: string | null
      mimeType: string | null
      metadata: {
        lqip: string | null
        dimensions: {
          width: number
          height: number
          aspectRatio: number
        } | null
      } | null
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
    caption: string | null
  }> | null
  tags: Array<{
    _id: string
    _type: 'tag'
    name: string
    slug: string
  }> | null
  seo: {
    title: string | null
    description: string | null
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
  } | null
} | null

// Source: ../frontend/src/data/sanity/queries.ts
// Variable: ALL_PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)] | order(orderRank asc, name asc) {    _id,  _type,  name,  slug,  coverImage {   asset->{    _id,    url,    mimeType,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  hotspot,  crop },  description}
export type ALL_PROJECTS_QUERY_RESULT = Array<{
  _id: string
  _type: 'project'
  name: string
  slug: Slug
  coverImage: {
    asset: {
      _id: string
      url: string | null
      mimeType: string | null
      metadata: {
        lqip: string | null
        dimensions: {
          width: number
          height: number
          aspectRatio: number
        } | null
      } | null
    } | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  }
  description: string | null
}>

// Source: ../frontend/src/data/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage"][0] {  _id,  _type,  title,  content[] {   ...,  markDefs[] {    ...,    _type == "link" => {   ...,  internalLink->{ _type, _id, "slug": slug.current, title } }  } },    seo {    title,    description,    image  }}
export type ABOUT_PAGE_QUERY_RESULT = {
  _id: string
  _type: 'aboutPage'
  title: string
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs: Array<{
          _key: string
          _type: 'link'
          text?: string
          type: string
          internalLink:
            | {
                _type: 'aboutPage'
                _id: string
                slug: null
                title: string
              }
            | {
                _type: 'homePage'
                _id: string
                slug: null
                title: string
              }
            | {
                _type: 'page'
                _id: string
                slug: string
                title: string
              }
            | {
                _type: 'project'
                _id: string
                slug: string
                title: null
              }
            | {
                _type: 'projectsIndex'
                _id: string
                slug: null
                title: string
              }
            | null
          url?: string
          email?: string
          phone?: string
          value?: string
          blank?: boolean
          parameters?: string
          anchor?: string
        }> | null
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
        markDefs: null
      }
  > | null
  seo: {
    title: string | null
    description: string | null
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
  } | null
} | null

// Source: ../frontend/src/data/sanity/queries.ts
// Variable: PROJECTS_INDEX_QUERY
// Query: *[_type == "projectsIndex"][0] {  _id,  _type,  title,  filters[]->{   _id,  _type,  name,  "slug": slug.current },    seo {    title,    description,    image  }}
export type PROJECTS_INDEX_QUERY_RESULT = {
  _id: string
  _type: 'projectsIndex'
  title: string
  filters: Array<{
    _id: string
    _type: 'tag'
    name: string
    slug: string
  }> | null
  seo: {
    title: string | null
    description: string | null
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
  } | null
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "settings"][0]': SETTINGS_QUERY_RESULT
    '*[_type == "homePage"][0] {\n  _id,\n  _type,\n  title,\n  description,\n  content[] { \n  ...,\n  markDefs[] {\n    ...,\n    _type == "link" => { \n  ...,\n  internalLink->{ _type, _id, "slug": slug.current, title }\n }\n  }\n },\n  featuredProjects[]->{ \n  _id,\n  _type,\n  name,\n  slug,\n  coverImage { \n  asset->{\n    _id,\n    url,\n    mimeType,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  hotspot,\n  crop\n },\n  description\n },\n  \n  seo {\n    title,\n    description,\n    image\n  }\n\n}': HOME_PAGE_QUERY_RESULT
    '*[_type == "page" && slug.current == $slug][0] {\n  _id,\n  _type,\n  title,\n  slug,\n  content[] { \n  ...,\n  markDefs[] {\n    ...,\n    _type == "link" => { \n  ...,\n  internalLink->{ _type, _id, "slug": slug.current, title }\n }\n  }\n },\n  \n  seo {\n    title,\n    description,\n    image\n  }\n\n}': PAGE_QUERY_RESULT
    '*[_type == "page" && defined(slug.current)] {\n  _id,\n  title,\n  slug\n}': ALL_PAGES_QUERY_RESULT
    '*[_type == "project" && slug.current == $slug][0] {\n  \n  \n  _id,\n  _type,\n  name,\n  slug,\n  coverImage { \n  asset->{\n    _id,\n    url,\n    mimeType,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  hotspot,\n  crop\n },\n  description\n,\n  gallery[] {\n    \n  _key,\n  \n  asset->{\n    _id,\n    url,\n    mimeType,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  hotspot,\n  crop\n,\n  caption\n\n  },\n  tags[]->{\n    \n  _id,\n  _type,\n  name,\n  "slug": slug.current\n\n  },\n  \n  seo {\n    title,\n    description,\n    image\n  }\n\n\n}': PROJECT_QUERY_RESULT
    '*[_type == "project" && defined(slug.current)] | order(orderRank asc, name asc) {\n  \n  _id,\n  _type,\n  name,\n  slug,\n  coverImage { \n  asset->{\n    _id,\n    url,\n    mimeType,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  hotspot,\n  crop\n },\n  description\n\n}': ALL_PROJECTS_QUERY_RESULT
    '*[_type == "aboutPage"][0] {\n  _id,\n  _type,\n  title,\n  content[] { \n  ...,\n  markDefs[] {\n    ...,\n    _type == "link" => { \n  ...,\n  internalLink->{ _type, _id, "slug": slug.current, title }\n }\n  }\n },\n  \n  seo {\n    title,\n    description,\n    image\n  }\n\n}': ABOUT_PAGE_QUERY_RESULT
    '*[_type == "projectsIndex"][0] {\n  _id,\n  _type,\n  title,\n  filters[]->{ \n  _id,\n  _type,\n  name,\n  "slug": slug.current\n },\n  \n  seo {\n    title,\n    description,\n    image\n  }\n\n}': PROJECTS_INDEX_QUERY_RESULT
  }
}
